### ISSUE TITLE
extension on firefox has new release, code is missing in here.

### ISSUE THREAD

**Issue by mdujava** [ibtisammidlet/youtube-watched-videos-hider#2]
Is there another source from where plugin is build?

https://addons.mozilla.org/en-US/firefox/addon/youtube-watched-videos-hider/

**Comment by ibtisammidlet** [comment]
> Is there another source from where plugin is build?
> 
> https://addons.mozilla.org/en-US/firefox/addon/youtube-watched-videos-hider/

i published all the documents
